default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: my_brag_development

test:
  <<: *default
  database: my_brag_test
  

production:
  <<: *default
  database: my_brag_production
