default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: my_brag_development

test:
  <<: *default
  database: my_brag_test
  username: <%= ENV['POSTGRES_USER']%>
  password: <%= ENV['POSTGRES_PASSWORD']%>
  host: localhost
  port: 5432
  

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: my_brag_production
  username: postgres
  password: <%= ENV["MY_BRAG_DATABASE_PASSWORD"] %>

cable:
  url: <%= ENV["DATABASE_URL"] %>

queue:
  url: <%= ENV["DATABASE_URL"] %>

cache:
  url: <%= ENV["DATABASE_URL"] %>
