env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: my_brag_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          bundle install
          yarn install --frozen-lockfile || true

      - name: Setup database
        run: |
          cp config/database.yml.github config/database.yml
          bin/rails db:prepare

      - name: Run tests
        run: bundle exec rspec
